services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    env_file:
      - ./backend/.env
    image: parshu8203/student-attendance-system-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: parshu8203/student-attendance-system-frontend:latest
