services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    env_file:
      - ./backend/.env
    image: parshu8203/student-attendance-system-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: parshu8203/student-attendance-system-frontend:latest
  qrpanel:
    build:
      context: ./qrpanel
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - frontend
    image: parshu8203/student-attendance-system-qrpanel:latest
  mobileapp:
    build:
      context: ./mobileapp
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: parshu8203/student-attendance-system-mobileapp:latest
